#pragma once
// 枚举返回类型
enum CODE {
	SUCCESS,
	FAILED,
	UNKNOWN,
	NO_SUCH_FILE,
	PERMISSION_DENIED,
	NOT_ENOUGH_STORAGE,
	DUPLICATED,
	INCORRECT_PASSWORD,
	WRONG_PARAMETER,
	INVALID_PASSWORD,
	NO_SUCH_DIRECTORY,
	INVALID_OPERATION,
	OTHER_ERROR
};